BoxOfVegs.Web/ViewModels/SharedViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BoxOfVegs.Web.ViewModels
{
    

    public class Pager
    {
        public Pager(int totalItems, int? page, int pageSize = 10)
        {
            if (pageSize == 0) pageSize = 10;

            var totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            var currentPage = page != null ? (int)page : 1;
            var startPage = currentPage - 5;
            var endPage = currentPage + 4;
            if (startPage <= 0)
            {
                endPage -= (startPage - 1);
                startPage = 1;
            }
            if (endPage > totalPages)
            {
                endPage = totalPages;
                if (endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }

            TotalItems = totalItems;
            CurrentPage = currentPage;
            PageSize = pageSize;
            TotalPages = totalPages;
            StartPage = startPage;
            EndPage = endPage;
        }

        public int TotalItems { get; private set; }
        public int CurrentPage { get; private set; }
        public int PageSize { get; private set; }
        public int TotalPages { get; private set; }
        public int StartPage { get; private set; }
        public int EndPage { get; private set; }
    }
}

BoxOfVegs.Web/Controllers/CategoryController.cs
using BoxOfVegs.Database;
using BoxOfVegs.Entities;
using BoxOfVegs.Services;
using BoxOfVegs.Web.ViewModels;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BoxOfVegs.Web.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        
        BOVContext context = new BOVContext();
       
        ServicesForCategories services = new ServicesForCategories();
        public ActionResult Index()
        {
            if (Convert.ToInt32(Session["UserRoleID"]) == 1)
            {
                return View();
            }
            return RedirectToAction("Login", "User");
        }

       

        public ActionResult Categories(string search, int? pageNO)
        {
            if (Convert.ToInt32(Session["UserRoleID"]) == 1)
            {
                CategoryPagingModels model = new CategoryPagingModels();

            model.Searching = search;
            int pageSize = 5;
           
            pageNO = pageNO.HasValue ? pageNO.Value > 0 ? pageNO.Value : 1 : 1;
            var totalRec = services.GetCountOfCategories(search);
            model.category = services.GetCategoriesList(search, pageNO.Value);
            if (model.category != null)
            {
                model.Pager = new Pager(totalRec, pageNO, pageSize);

                return PartialView("Categories", model);
            }
            else
            {
                return HttpNotFound();
            }
            }
            return RedirectToAction("Login", "User");
        }

       
        [HttpGet]
        public ActionResult AddCategory()
        {
            if (Convert.ToInt32(Session["UserRoleID"]) == 1)
            {

                return View();
            }
            return RedirectToAction("Login", "User");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCategory(Category category, HttpPostedFileBase file)
        {
            if (Convert.ToInt32(Session["UserRoleID"]) == 1)
            {
                if (ModelState.IsValid)
            {
                string fileName = null;
            if (file != null)
            {
                string extension = System.IO.Path.GetExtension(file.FileName);
                string newName = Guid.NewGuid().ToString();
                fileName = newName + extension;
                string path = System.IO.Path.Combine(Server.MapPath("~/Content/images/category/"), fileName);
                // file is uploaded
                file.SaveAs(path);
            }
            

            category.ImageUrl = fileName;
            services.AddCategory(category);
            return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "");
            }
            return View();
            }
            return RedirectToAction("Login", "User");
        }
        [HttpGet]
        public ActionResult UpdateCategory(int categoryID)
        {
            if (Convert.ToInt32(Session["UserRoleID"]) == 1)
            {

                var category= services.GetCategory(categoryID);
            category.ImageUrl = category.ImageUrl;
            return View(category);
            }
            return RedirectToAction("Login", "User");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult UpdateCategory(Category category, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
            if (file != null)
            {
                    string extension = System.IO.Path.GetExtension(file.FileName);
                    string newName = Guid.NewGuid().ToString();
                    fileName = newName + extension;
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/images/category/"), fileName);
                // file is uploaded
                file.SaveAs(path);
            
                category.ImageUrl = fileName;
            }
            else
            {
                var categories = services.GetCategory(category.CategoryID);
                category.ImageUrl = categories.ImageUrl;
            }
           

            services.UpdateCategory(category);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "");
            }
            return View();
        }
        public ActionResult DeleteCategory(int categoryID)
        {
            if (Convert.ToInt32(Session["UserRoleID"]) == 1)
            {
                var category = services.GetCategory(categoryID);

                return View(category);
            }
            return RedirectToAction("Login", "User");
        }

        [HttpPost]
        public ActionResult DeleteCategory(Category category)
        {
            if (Convert.ToInt32(Session["UserRoleID"]) == 1)
            {

                services.DeleteCategoryWithRange(category);

            return RedirectToAction("Index");
            }
            return RedirectToAction("Login", "User");
        }

    }
}

BoxOfVegs.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BoxOfVegs.Web.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

BoxOfVegs.Web/Controllers/ShopController.cs
using BoxOfVegs.Database;
using BoxOfVegs.Entities;
using BoxOfVegs.Services;
using BoxOfVegs.Web.ViewModels;
using Rotativa.MVC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BoxOfVegs.Web.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        ServicesForCategories categoryService = new ServicesForCategories();
        ServicesForProducts productService = new ServicesForProducts();
        ServicesForShop shopService = new ServicesForShop();
        BOVContext context = new BOVContext();

        public ActionResult Index(string search, int? minPrice, int? maxPrice, int? categoryID, int? sortBy)
        {
           

            ShopProductViewModel model = new ShopProductViewModel
            {
                ShopSearching = search,
                ShopCategories = categoryService.AllCategories(),
                MaximumPrice = productService.GetMaxPrice()
            };

            model.SortBy = sortBy;
            model.CategoryID = categoryID;

            model.ShopProducts = productService.ShopProducts(search, minPrice, maxPrice, categoryID, sortBy);


            return View(model);
        }
        public ActionResult AddInCart(int productId, int qty)
        {
            List<CartViewModel> list = new List<CartViewModel>();
            var product = productService.GetProduct(productId);
            CartViewModel crt = new CartViewModel
            {
                ProductID = product.ProductID,
                Price = product.Price,
                Quanity = qty,
                TotalQuantity=product.Quantity,
                ProductURL=product.ImageUrl
            };
            crt.Subtotal = crt.Price * crt.Quanity;
            crt.ProductName = product.ProductName;
            if (Session["cart"] == null)
            {
                list.Add(crt);
                Session["cart"] = list;

            }
            else
            {
                List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
                int change = 0;
                foreach (var item in newlist)
                {
                    if (item.ProductID == crt.ProductID)
                    {
                        item.Quanity += crt.Quanity;
                        item.Subtotal += crt.Subtotal;
                        change = 1;

                    }
                }
                if (change==0)
                {
                    newlist.Add(crt);
                }
                Session["cart"] = newlist;
            }

            if (Session["cart"] != null)
            {
                Decimal x = 0;
                List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
                foreach (var item in newlist)
                {
                    x += item.Subtotal;

                }

                Session["total"] = x;
            }
            
            return RedirectToAction("Cart");
        }
       
        public ActionResult DeleteFromCart(int productId)
        {
            List<CartViewModel> cart = (List<CartViewModel>)Session["cart"];
            foreach (var item in cart)
            {
                if (item.ProductID == productId)
                {
                    cart.Remove(item);
                    break;
                }
            }
            Session["cart"] = cart;
            if (Session["cart"] != null)
            {
                Decimal x = 0;
                List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
                foreach (var item in newlist)
                {
                    x += item.Subtotal;

                }

                Session["total"] = x;
            }
            return RedirectToAction("Cart");
        }
        public ActionResult Cart()
        {
            if (Session["UserID"] != null)
            {
                if (Session["cart"] != null)
                {
                Decimal x = 0;
                List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
                foreach (var item in newlist)
                {
                    x += item.Subtotal;

                }

                Session["total"] = x;
                }
                 return View();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
        public ActionResult Checkout()
        {
            if (Session["cart"] != null)
            {
                Decimal x = 0;
                List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
                foreach (var item in newlist)
                {
                    x += item.Subtotal;

                }

                Session["total"] = x;
            }

            return View();
        }
        [HttpPost]      
        public ActionResult Checkout( FormCollection formData)
        {
            
                if (Session["UserID"] != null)
                {
                  if(Session["cart"] != null)
                  {
                   
                       List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
                    int userID = Convert.ToInt32(Session["UserID"].ToString());

                    Invoice invoice = new Invoice
                    {
                        
                        UserID = userID,
                        TotalAmount = (decimal)Session["total"],
                        InvoiceDate = DateTime.Now,
                        Address = Convert.ToString(formData["street"]),
                        City = Convert.ToString(formData["city"]),
                        PostCode = Convert.ToString(formData["postCode"]),
                        PhoneNumber = Convert.ToString(formData["phone"])
                    };
                    shopService.AddInvoice(invoice);
                    foreach (var item in newlist)
                    {
                        Order orders = new Order
                        {
                            ProductID = item.ProductID,
                            InvoiceID = invoice.InvoiceID,
                            ProductName = item.ProductName,
                            Quantity = item.Quanity,
                            Date = DateTime.Now,
                            UnitPrice = item.Price,
                            Subtotal = item.Subtotal
                        };
                        int newQuantity = (item.TotalQuantity - item.Quanity);
                         shopService.AddOrder(orders);
                        productService.UpdateQuantity(item.ProductID,newQuantity);
                    }
                    Session.Remove("total");
                    Session.Remove("cart");
                    return RedirectToAction("Invoice", new { userId = userID });
                   
                }
                else
                {
                    return RedirectToAction("Cart");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
        public ActionResult UpdateCart(FormCollection formData)
        {
            string[] quantities = formData.GetValues("qty");
            List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
            decimal x = 0;
            for (int i = 0; i < newlist.Count; i++)
            {
                newlist[i].Quanity = Convert.ToInt32(quantities[i]);
                newlist[i].Subtotal = newlist[i].Price * newlist[i].Quanity;
                Session["cart"] = newlist;
                x += newlist[i].Subtotal;

            }



            Session["total"] = x;
            return View("Cart");
        }
        public ActionResult Invoice()
        {
            return View();
        }
        public ActionResult CreateInvoice(int userId)
        {
            
            var invoiceDetails = shopService.GetInvoiceDetail(userId);
            var userDetails = shopService.GetUserDetails(userId);
            int invoiceId = invoiceDetails.InvoiceID;
            InvoiceDetailViewModel model = new InvoiceDetailViewModel
            {
                Orders = shopService.GetOrders(invoiceId),
                UserID = userId,
                InvoiceDate = invoiceDetails.InvoiceDate,
                InvoiceID = invoiceId,
                PhoneNumber = invoiceDetails.PhoneNumber,
                PostCode = invoiceDetails.PostCode,
                TotalAmount = invoiceDetails.TotalAmount,
                Address = invoiceDetails.Address,
                City = invoiceDetails.City,
                FirstName = userDetails.FirstName,
                LastName = userDetails.LastName
            };

            return PartialView("CreateInvoice", model);
        }
        public ActionResult PrintInvoice(int userid)
        {
            return new ActionAsPdf("CreateInvoice", new { userid });

        }
        public ActionResult YourOrder()
        {
            if (Session["UserID"] != null)
            {
                int userId = Convert.ToInt32(Session["UserID"].ToString());
                var orderRecords = context.Orders.Join(context.Invoices, o => o.InvoiceID, i => i.InvoiceID, (o, i) => new { o, i })
                                                .Where(u => u.i.UserID == userId).OrderByDescending(u=>u.i.InvoiceDate)
                                                .Select(u => new OrdersVeiwModel
                                                {
                                                    OrderID= u.o.OrderID,
                                                    ProductID= u.o.ProductID,
                                                    ProductName= u.o.ProductName,
                                                    Quantity=u.o.Quantity,
                                                    Product= u.o.Product,

BoxOfVegs.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @*<link href="~/Content/css/admin.css" rel="stylesheet" />*@
    @*<script src="~/Content/RateYo/jquery.min.js"></script>*@
    <!-- Custom fonts for this template-->
    @* <link href="~/Content/AdminStyle/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">*@

    <!-- Page level plugin CSS-->
    <link href="~/Content/AdminStyle/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/AdminStyle/css/sb-admin.css" rel="stylesheet">

    <link href="~/Content/AdminStyle/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />

    <script src="~/Content/AdminStyle/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/AdminStyle/js/sb-admin.min.js"></script>
</head>
<body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
        <a class="navbar-brand mr-1" href="../Admin/Dashboard">BoxOfVegs</a>

        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>

        @*<h4 class="navbar-brand">BoxOfVegs</h4>*@
        @*<a href="@Url.Action("Index", "Home")" style="text-align:center"><span style="color:white">Back to Customer Panel</span></a>*@

        @*<a href="@Url.Action("Logout", "User")" style="text-align:right"><span style="color:red">Logout</span></a>*@

        <!-- Navbar Search -->
        <div class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            @*<div class="input-group">
                <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>*@
        </div>
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-bell fa-fw"></i>
                    <span class="badge badge-danger">9+</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                

                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-envelope fa-fw"></i>
                    @*<span class="badge badge-danger">7</span>*@
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-fw"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a>
                    <a class="dropdown-item" href="#">Activity Log</a>
                    <a class="dropdown-item" href="@Url.Action("Index", "Home")">Customer Panel</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" href="@Url.Action("Logout", "User")" @*data-toggle="modal" data-target="#logoutModal"*@>Logout</a>
                </div>
            </li>
        </ul>


    </nav>

    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index", "Dashboard")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Category")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Categories</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Product")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Products</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Orders</span>
                </a>
            </li>
        </ul>

        <div id="content-wrapper">



            @RenderBody()




        </div>

        <footer class="sticky-footer">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright © 2019 - All Rights Reserved.</span>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.content-wrapper -->
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    @*<script src="~/Content/AdminStyle/vendor/jquery/jquery.min.js"></script>*@
    <script src="~/Content/AdminStyle/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/AdminStyle/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Page level plugin JavaScript-->
    <script src="~/Content/AdminStyle/vendor/chart.js/Chart.min.js"></script>
    <script src="~/Content/AdminStyle/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/Content/AdminStyle/vendor/datatables/dataTables.bootstrap4.js"></script>

    <!-- Custom scripts for all pages-->
    @*<script src="~/Content/AdminStyle/js/sb-admin.min.js"></script>*@

    <!-- Demo scripts for this page-->
    <script src="~/Content/AdminStyle/js/demo/datatables-demo.js"></script>
    <script src="~/Content/AdminStyle/js/demo/chart-area-demo.js"></script>


</body>

</html>