BoxOfVegs.Web/ViewModels/InvoiceViewModels.cs
using BoxOfVegs.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BoxOfVegs.Web.ViewModels
{
	public class InvoiceDetailViewModel
	{
		public List<Order> Orders { get; set; }
		public int UserID { get; set; }
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public int InvoiceID { get; set; }
		public string Address { get; set; }

		public string PostCode { get; set; }

		public string City { get; set; }
		public string PhoneNumber { get; set; }
		public DateTime InvoiceDate { get; set; }
		public decimal TotalAmount { get; set; }
		
	}
}

BoxOfVegs.Web/ViewModels/ShopViewModels.cs
using BoxOfVegs.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BoxOfVegs.Web.ViewModels
{
    public class ShopProductViewModel
    {
        public int MaximumPrice { get; set; }
        public List<Category> ShopCategories { get; set; }
        public List<Product> ShopProducts { get; set; }
        public int? SortBy { get; set; }
        public int? CategoryID { get; set; }

        public Pager ShopPager { get; set; }
        public string ShopSearching { get; set; }
    }
    public class CartViewModel
    {

        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductURL { get; set; }
        public int TotalQuantity { get; set; }
        public Decimal Price { get; set; }
        public int Quanity { get; set; }
        public Decimal Subtotal { get; set; }
        
    }
    public class OrdersVeiwModel
    {
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public Product Product { get; set; }
        public Decimal Subtotal { get; set; }
        public Decimal UnitPrice { get; set; }
        public Invoice Invoice { get; set; }
        public DateTime InvoiceDate { get; set; }
        public int UserID { get; set; }
        public User User { get; set; }
        public string PostCode { get; set; }
        public string Address { get; set; }
        public string City { get; set; }

    }

}

BoxOfVegs.Web/Controllers/ShopController.cs
using BoxOfVegs.Database;
using BoxOfVegs.Entities;
using BoxOfVegs.Services;
using BoxOfVegs.Web.ViewModels;
using Rotativa.MVC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BoxOfVegs.Web.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        ServicesForCategories categoryService = new ServicesForCategories();
        ServicesForProducts productService = new ServicesForProducts();
        ServicesForShop shopService = new ServicesForShop();
        BOVContext context = new BOVContext();

        public ActionResult Index(string search, int? minPrice, int? maxPrice, int? categoryID, int? sortBy)
        {
           

            ShopProductViewModel model = new ShopProductViewModel
            {
                ShopSearching = search,
                ShopCategories = categoryService.AllCategories(),
                MaximumPrice = productService.GetMaxPrice()
            };

            model.SortBy = sortBy;
            model.CategoryID = categoryID;

            model.ShopProducts = productService.ShopProducts(search, minPrice, maxPrice, categoryID, sortBy);


            return View(model);
        }
        public ActionResult AddInCart(int productId, int qty)
        {
            List<CartViewModel> list = new List<CartViewModel>();
            var product = productService.GetProduct(productId);
            CartViewModel crt = new CartViewModel
            {
                ProductID = product.ProductID,
                Price = product.Price,
                Quanity = qty,
                TotalQuantity=product.Quantity,
                ProductURL=product.ImageUrl
            };
            crt.Subtotal = crt.Price * crt.Quanity;
            crt.ProductName = product.ProductName;
            if (Session["cart"] == null)
            {
                list.Add(crt);
                Session["cart"] = list;

            }
            else
            {
                List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
                int change = 0;
                foreach (var item in newlist)
                {
                    if (item.ProductID == crt.ProductID)
                    {
                        item.Quanity += crt.Quanity;
                        item.Subtotal += crt.Subtotal;
                        change = 1;

                    }
                }
                if (change==0)
                {
                    newlist.Add(crt);
                }
                Session["cart"] = newlist;
            }

            if (Session["cart"] != null)
            {
                Decimal x = 0;
                List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
                foreach (var item in newlist)
                {
                    x += item.Subtotal;

                }

                Session["total"] = x;
            }
            
            return RedirectToAction("Cart");
        }
       
        public ActionResult DeleteFromCart(int productId)
        {
            List<CartViewModel> cart = (List<CartViewModel>)Session["cart"];
            foreach (var item in cart)
            {
                if (item.ProductID == productId)
                {
                    cart.Remove(item);
                    break;
                }
            }
            Session["cart"] = cart;
            if (Session["cart"] != null)
            {
                Decimal x = 0;
                List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
                foreach (var item in newlist)
                {
                    x += item.Subtotal;

                }

                Session["total"] = x;
            }
            return RedirectToAction("Cart");
        }
        public ActionResult Cart()
        {
            if (Session["UserID"] != null)
            {
                if (Session["cart"] != null)
                {
                Decimal x = 0;
                List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
                foreach (var item in newlist)
                {
                    x += item.Subtotal;

                }

                Session["total"] = x;
                }
                 return View();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
        public ActionResult Checkout()
        {
            if (Session["cart"] != null)
            {
                Decimal x = 0;
                List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
                foreach (var item in newlist)
                {
                    x += item.Subtotal;

                }

                Session["total"] = x;
            }

            return View();
        }
        [HttpPost]      
        public ActionResult Checkout( FormCollection formData)
        {
            
                if (Session["UserID"] != null)
                {
                  if(Session["cart"] != null)
                  {
                   
                       List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
                    int userID = Convert.ToInt32(Session["UserID"].ToString());

                    Invoice invoice = new Invoice
                    {
                        
                        UserID = userID,
                        TotalAmount = (decimal)Session["total"],
                        InvoiceDate = DateTime.Now,
                        Address = Convert.ToString(formData["street"]),
                        City = Convert.ToString(formData["city"]),
                        PostCode = Convert.ToString(formData["postCode"]),
                        PhoneNumber = Convert.ToString(formData["phone"])
                    };
                    shopService.AddInvoice(invoice);
                    foreach (var item in newlist)
                    {
                        Order orders = new Order
                        {
                            ProductID = item.ProductID,
                            InvoiceID = invoice.InvoiceID,
                            ProductName = item.ProductName,
                            Quantity = item.Quanity,
                            Date = DateTime.Now,
                            UnitPrice = item.Price,
                            Subtotal = item.Subtotal
                        };
                        int newQuantity = (item.TotalQuantity - item.Quanity);
                         shopService.AddOrder(orders);
                        productService.UpdateQuantity(item.ProductID,newQuantity);
                    }
                    Session.Remove("total");
                    Session.Remove("cart");
                    return RedirectToAction("Invoice", new { userId = userID });
                   
                }
                else
                {
                    return RedirectToAction("Cart");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
        public ActionResult UpdateCart(FormCollection formData)
        {
            string[] quantities = formData.GetValues("qty");
            List<CartViewModel> newlist = (List<CartViewModel>)Session["cart"];
            decimal x = 0;
            for (int i = 0; i < newlist.Count; i++)
            {
                newlist[i].Quanity = Convert.ToInt32(quantities[i]);
                newlist[i].Subtotal = newlist[i].Price * newlist[i].Quanity;
                Session["cart"] = newlist;
                x += newlist[i].Subtotal;

            }



            Session["total"] = x;
            return View("Cart");
        }
        public ActionResult Invoice()
        {
            return View();
        }
        public ActionResult CreateInvoice(int userId)
        {
            
            var invoiceDetails = shopService.GetInvoiceDetail(userId);
            var userDetails = shopService.GetUserDetails(userId);
            int invoiceId = invoiceDetails.InvoiceID;
            InvoiceDetailViewModel model = new InvoiceDetailViewModel
            {
                Orders = shopService.GetOrders(invoiceId),
                UserID = userId,
                InvoiceDate = invoiceDetails.InvoiceDate,
                InvoiceID = invoiceId,
                PhoneNumber = invoiceDetails.PhoneNumber,
                PostCode = invoiceDetails.PostCode,
                TotalAmount = invoiceDetails.TotalAmount,
                Address = invoiceDetails.Address,
                City = invoiceDetails.City,
                FirstName = userDetails.FirstName,
                LastName = userDetails.LastName
            };

            return PartialView("CreateInvoice", model);
        }
        public ActionResult PrintInvoice(int userid)
        {
            return new ActionAsPdf("CreateInvoice", new { userid });

        }
        public ActionResult YourOrder()
        {
            if (Session["UserID"] != null)
            {
                int userId = Convert.ToInt32(Session["UserID"].ToString());
                var orderRecords = context.Orders.Join(context.Invoices, o => o.InvoiceID, i => i.InvoiceID, (o, i) => new { o, i })
                                                .Where(u => u.i.UserID == userId).OrderByDescending(u=>u.i.InvoiceDate)
                                                .Select(u => new OrdersVeiwModel
                                                {
                                                    OrderID= u.o.OrderID,
                                                    ProductID= u.o.ProductID,
                                                    ProductName= u.o.ProductName,
                                                    Quantity=u.o.Quantity,
                                                    Product= u.o.Product,

BoxOfVegs.Web/Views/Shop/Cart.cshtml
@{
    ViewBag.Title = "Cart";
}

@{
    var imageURL = "placeholder-image.png";
}


<div class="ogami-breadcrumb">
    <div class="container">
        <ul>
            <li> <a class="breadcrumb-link" href="@Url.Action("Index", "Home")">Home</a></li>
            <li> <a class="breadcrumb-link" href="@Url.Action("Index", "Shop")">Shop</a></li>
            <li> <a class="breadcrumb-link active">Shoping cart</a></li>
        </ul>
    </div>
</div>

<div class="shopping-cart">
    <div class="container">
        @using (Html.BeginForm("UpdateCart", "Shop", FormMethod.Post))
        {
            <div class="row">
                <div class="col-12">
                    <div class="product-table">
                        <table class="table table-responsive">
                            <colgroup>
                                <col span="1" style="width: 15%">
                                <col span="1" style="width: 30%">
                                <col span="1" style="width: 15%">
                                <col span="1" style="width: 15%">
                                <col span="1" style="width: 15%">
                                <col span="1" style="width: 10%">
                            </colgroup>

                            <thead>
                                <tr>
                                    <th class="product-iamge" scope="col">Image</th>
                                    <th class="product-name" scope="col">Product name</th>
                                    <th class="product-price" scope="col">Price</th>
                                    <th class="product-quantity" scope="col">Quantity</th>
                                    <th class="product-total" scope="col">Total</th>
                                    <th class="product-clear" scope="col">
                                        <button class="no-round-btn"><i class="icon_close"></i></button>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Session["cart"] != null)
                                {

                                    foreach (var item in (List<CartViewModel>)Session["cart"])
                                    {
                                        var imageUrl = string.IsNullOrEmpty(item.ProductURL) ? imageURL : item.ProductURL;

                                        <tr>
                                            <td class="product-iamge">
                                                <div class="img-wrapper"><img src="~/Content/images/product/@imageUrl" alt="product image"></div>
                                            </td>
                                            <td class="product-name">@item.ProductName</td>
                                            <td class="product-price">£ @item.Price</td>
                                            <td class="product-quantity">
                                                <input class="quantity no-round-input" type="number" min="1" max="@item.TotalQuantity" value="@item.Quanity" name="qty">
                                            </td>
                                            <td class="product-total">£@item.Subtotal</td>
                                            <td class="product-clear">
                                                <a href="@Url.Action("DeleteFromCart", "Shop", new { productId = item.ProductID })"><i class="icon_close"></i></a>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-12 col-sm-8">
                    <input class="no-round-btn smooth" type='button' value='Back To Shoping' onclick='window.location = "@Url.Action("Index", "Shop")";' />
                </div>
                   
                <div class="col-12 col-sm-4 text-right">
                    <button class="no-round-btn black cart-update" type="submit">Upadate cart</button>
                </div>
            
            </div>
        }
        <div class="row justify-content-end">
            <div class="col-12 col-md-6 col-lg-4">
                <div class="cart-total_block">
                    <h2>Cart total</h2>
                    <table class="table">
                        <colgroup>
                            <col span="1" style="width: 50%">
                            <col span="1" style="width: 50%">
                        </colgroup>
                        <tbody>
                            <tr>
                                <th>SUBTOTAL</th>
                                <td>£@Session["total"]</td>
                            </tr>
                            <tr>
                                <th>SHIPPING</th>
                                <td>
                                    <p>Free shipping</p>

                                </td>
                            </tr>
                            <tr>
                                <th>TOTAL</th>
                                <td>£@Session["total"]</td>
                            </tr>
                        </tbody>
                    </table>
                    @if (Session["cart"] != null)
                    {
                        
                            <div class="checkout-method">
                                <button class="normal-btn" onclick='window.location = "@Url.Action("Checkout", "Shop")";'>Proceed to Checkout</button>
                            </div>
                           
                        }

                </div>
            </div>
        </div>
    </div>
</div>

BoxOfVegs.Web/Views/Shop/Checkout.cshtml
@{
    ViewBag.Title = "Checkout";
}


<div class="ogami-breadcrumb">
    <div class="container">
        <ul>
            <li> <a class="breadcrumb-link" href="@Url.Action("Index", "Home")">Home</a></li>
            <li> <a class="breadcrumb-link" href="@Url.Action("Index", "Shop")">Shop</a></li>
            <li> <a class="breadcrumb-link" href="@Url.Action("Cart", "Shop")">Cart</a></li>
            <li><a class="breadcrumb-link active">Checkout</a></li>
        </ul>
    </div>
</div>

<div class="shop-checkout">
    <div class="container">
        <form action="" method="post">
            <div class="row">
                <div class="col-12 col-lg-8">
                    <h2 class="form-title">Shipping details</h2>
                    
                    <div class="form-group">
                        <label for="inputCountry">Country*</label>
                        <input class="no-round-input-bg" type="text" required value="United Kingdom" name="country">
                    </div>
                    <div class="form-group">
                        <label for="inputStreet">Street address*</label>
                        <input class="no-round-input-bg" id="inputStreet" type="text" required name="street">
                    </div>
                    <div class="form-group">
                        <label for="inputZip">Postcode / ZIP*</label>
                        <input class="no-round-input-bg" id="inputZip" type="text" name="postCode">
                    </div>
                    <div class="form-group">
                        <label for="inputCity">Town / City*</label>
                        <input class="no-round-input-bg" id="inputCity" type="text" required value="Leicester" name="city">
                    </div>
                    <div class="form-group">
                        <label for="inputPhone">Phone*</label>
                        <input class="no-round-input-bg" id="inputPhone" type="tel" pattern="[0-9]{11}" name="phone" required>
                        <span>Format: 07123456789</span>
                    </div>
                    
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <h2 class="form-title">Your order</h2>
                    <div class="shopping-cart">
                        <div class="cart-total_block">
                            <table class="table">
                                <colgroup>
                                    <col span="1" style="width: 50%">
                                    <col span="1" style="width: 50%">
                                </colgroup>
                                <tbody>
                                    @if (Session["cart"] != null)
                                    {

                                        foreach (var item in (List<CartViewModel>)Session["cart"])
                                        {
                                            <tr>
                                                <th class="name">@item.ProductName × <span>@item.Quanity</span></th>
                                                <td class="price black" style="border-top: 0">£@item.Subtotal</td>
                                            </tr>
                                        }
                                    }
                                    <tr>
                                        <th>SUBTOTAL</th>
                                        <td class="price">£@Session["total"]</td>
                                    </tr>
                                    <tr>
                                        <th>SHIPPING</th>
                                        <td>
                                            <p>Free shipping</p>

                                        </td>
                                    </tr>
                                    <tr>
                                        <th>TOTAL</th>
                                        <td class="total">£@Session["total"]</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        @using (Html.BeginForm())
                        {
                        <button class="normal-btn submit-btn" type="submit">Place order</button>
                        }
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

BoxOfVegs.Web/Views/Shop/Index.cshtml
@model  ShopProductViewModel

@{
    ViewBag.Title = "Index";

}
@{ var imageURL = "placeholder-image.png"; }


<div class="ogami-breadcrumb">
    <div class="container">
        <ul>
            <li> <a class="breadcrumb-link" href="@Url.Action("Index", "Home")">Home</a></li>
            <li> <a class="breadcrumb-link active">Shop</a></li>
        </ul>
    </div>
</div>
<div class="shop-layout">
    <div class="container">
        <div class="row">
            <div class="col-xl-3">

                <div class="shop-sidebar">

                    <div class="shop-sidebar_department">

                        <div class="department_top mini-tab-title underline">
                            <h2 class="title">Departments</h2>

                        </div>
                        <div class="department_bottom">
                            @foreach (var item in Model.ShopCategories)
                            {

                                <a class="department-link filterLink @(Model.CategoryID.HasValue && Model.CategoryID.Value == item.CategoryID ? "active" : string.Empty)" href="@Url.Action("Index", "Shop", new { categoryID = item.CategoryID, sortBy = Model.SortBy })">@item.CategoryName</a>
                                <br />

                            }
                        </div>
                    </div>
                    <div class="shop-sidebar_department">
                        <div class="price-filter_top mini-tab-title underline">
                            <h2 class="title">Filter By</h2>
                        </div>
                        <div class="department_bottom">


                            <a href="@Url.Action("Index", "Shop", new { sortBy=1, categoryID = Model.CategoryID })" class=" department-link filterLink @(Model.SortBy.HasValue ? Model.SortBy.Value == 1 ? "active" : string.Empty : string.Empty)">Newest First</a>
                            <br />
                            <a href="@Url.Action("Index", "Shop", new { sortBy=2, categoryID = Model.CategoryID })" class=" department-link filterLink @(Model.SortBy.HasValue ? Model.SortBy.Value == 2 ? "active" : string.Empty : string.Empty)">Price: low to high</a>
                            <br />
                            <a href="@Url.Action("Index", "Shop", new { sortBy=3, categoryID = Model.CategoryID  })" class="department-link filterLink @(Model.SortBy.HasValue ? Model.SortBy.Value == 3  ? "active" : string.Empty : string.Empty)">Price: high to low</a>
                            <br />
                        </div>
                        <br />
                        <h4><a href="@Url.Action("Index", "Shop")">Reset Filter & Search</a></h4>
                       
                    </div>

                </div>
                <div class="filter-sidebar--background" style="display: none"></div>
            </div>
            <div class="col-xl-9">
                <div class="shop-grid-list">
                    <div class="shop-products">
                        <div class="shop-products_top mini-tab-title underline">
                            <div class="row align-items-center">
                                <div class="col-6 col-xl-4">
                                    <h2 class="title">Shop</h2>
                                </div>
                               
                            </div>
                        </div>
                        <div class="shop-products_bottom" id="shopproducts">
                            <div class="row no-gutters-sm">
                                @foreach (var item in Model.ShopProducts)
                                {
                                    var imageUrl = string.IsNullOrEmpty(item.ImageUrl) ? imageURL : item.ImageUrl;

                                    <div class="col-6 col-md-4">
                                        <div class="product">
                                            <div class="product-img_block">
                                                <a class="product-img" href="@Url.Action("ProductDetails", "Product", new { productId = item.ProductID })"><img src="~/Content/images/product/@imageUrl" alt=""></a>
                                            </div>
                                            <div class="product-info_block">
                                                <h5 class="product-type">@item.Category.CategoryName</h5>
                                                <a class="product-name">@item.ProductName</a>
                                                <h3 class="product-price">
                                                    £ @item.Price
                                                </h3>
                                                <h5 class="product-avaiable"><span>@item.Quantity In stock</span></h5>
                                            </div>
                                            <div class="product-select">
                                                @if(item.Quantity>0)
                                                { 
                                                  using (Html.BeginForm("AddInCart", "Shop", new {qty=1, productId = item.ProductID }, FormMethod.Post))
                                                  {
                                                    <button class="add-to-cart round-icon-btn" type="submit">Add To Cart</button>
                                                    }
                                                }
                                                else
                                                {
                                                    <p>Product not available</p>
                                                }
                                            </div>
                                           
                                        </div>
                                    </div>
                                }

                            </div>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(".filterLink").click(function () {
        var url = $(this).attr("data-href");

        if (url != "" || url != undefined) {
            GetData(url);
        }
    });
</script>

BoxOfVegs.Web/Views/Shop/Invoice.cshtml
@{
    ViewBag.Title = "Invoice";
}

<div class="container-fluid">


    <ol class="breadcrumb">

        <li class="breadcrumb-item active">Invoice</li>
    </ol>
    <div style="text-align:right">@Html.ActionLink("Print Invoice", "PrintInvoice", new { userid = Convert.ToInt32(Session["UserID"]) })</div>

    <div id="Invoice">
        @{
            Html.RenderAction("CreateInvoice");
        }
    </div>
</div>